### ISSUE TITLE
感觉您的项目很好，有些问题想要咨询

### ISSUE THREAD

**Issue by wnctrunk** [BluewhaleRobot/systemback#1]
如果我不需要安装我定制的ubuntu镜像，只需要livecd功能（ramos），我是否可以剔除掉casper这个组件？

**Comment by randoms** [comment]
不可以casper是必须的，整个系统的载入需要casper

**Comment by wnctrunk** [comment]
> 不可以casper是必须的，整个系统的载入需要casper

好的谢谢
