### ISSUE TITLE
无法获取秘钥

### ISSUE THREAD

**Issue by lugeliu** [BluewhaleRobot/systemback#11]
我在构建systemback时出错，无法获取秘钥。
错误信息：
N: 4 tags overridden (4 warnings)
Finished running lintian.
Now signing changes and any dsc files...
 signfile dsc systemback_1.8.8.dsc Bluewhale Robot <randoms@bwbot.org>
gpg: “Bluewhale Robot <randoms@bwbot.org>”已跳过：没有秘匙
gpg: /tmp/debsign.xPD7l4DT/systemback_1.8.8.dsc: clear-sign failed: 没有秘匙
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1081:
running debsign failed

我如何获取秘钥，谢谢。

**Comment by randoms** [comment]
可以忽略这个错误，这个是用来发布的，自己编译不需要发布

**Comment by lugeliu** [comment]
请问我如何避免这个错误，需要改哪里吗，我直接键入debuild后出现这个错误，systemback没有安装成功

**Comment by randoms** [comment]
运行debuild之后会生成一些deb文件，然后用dpkg安装这些deb文件。如果嫌麻烦也可以用README里面提到的软件源直接安装
