### ISSUE TITLE
An error occured while unpacking the live system files

### ISSUE THREAD

**Issue by OrdinaryChen** [BluewhaleRobot/systemback#13]
hello everyone, I create a live image and it is 42.38GB, when I white to a 64GB U-disk , an error occured. 
![Screenshot from 2021-06-08 17-16-11](https://user-images.githubusercontent.com/31204657/121162289-62917100-c880-11eb-934f-742e54a24e90.png)
I was in ubuntu 18.04.5 and is that mean my image is too big?
我在ubuntu18.04.05 上生成了一个镜像大小是42.38GB，我想把他装在一个64GB的U盘上但是写入的时候发生了这个错误，是我的镜像太大了吗，有大神知道为啥吗？？

**Comment by randoms** [comment]
是太大了，虽然整体的大小限制没有了，但是单个文件不超过4G的限制还在。现在代码里面的做法是把home和独立出来压缩一个文件。所以home太大了还是不行。还有一个做法就是不生成iso文件直接利用sblive文件写入u盘。

**Comment by OrdinaryChen** [comment]
> 是太大了，虽然整体的大小限制没有了，但是单个文件不超过4G的限制还在。现在代码里面的做法是把home和独立出来压缩一个文件。所以home太大了还是不行。还有一个做法就是不生成iso文件直接利用sblive文件写入u盘。

我就是不保存iso直接写进世界写入u盘的，之前系统20多g的时候写成功了的，现在40多g之后就写不了了

**Comment by renma1** [comment]
这个感觉跟sblive的文件大小有关

> 
> 
> > 是太大了，虽然整体的大小限制没有了，但是单个文件不超过4G的限制还在。现在代码里面的做法是把home和独立出来压缩一个文件。所以home太大了还是不行。还有一个做法就是不生成iso文件直接利用sblive文件写入u盘。
> 
> 我就是不保存iso直接写进世界写入u盘的，之前系统20多g的时候写成功了的，现在40多g之后就写不了了

这个写入U盘时，把U盘分成了2块SBLIVE和SBROOT，我看了下我写入错误时的错误报告，提示是其中一块100M的SBLIVE分区满了无法写入，所以这个应该需要修改源代码，把这个分区改大一些

**Comment by OrdinaryChen** [comment]
大老，具体怎么操作啊…代码怎么改…


 
---Original---
From: ***@***.***&gt;
Date: 2021/6/9 15:26:04
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BluewhaleRobot/systemback] An error occured while unpacking the live system files (#13)




 
这个感觉跟sblive的文件大小有关
   
是太大了，虽然整体的大小限制没有了，但是单个文件不超过4G的限制还在。现在代码里面的做法是把home和独立出来压缩一个文件。所以home太大了还是不行。还有一个做法就是不生成iso文件直接利用sblive文件写入u盘。
  
我就是不保存iso直接写进世界写入u盘的，之前系统20多g的时候写成功了的，现在40多g之后就写不了了
  
这个写入U盘时，把U盘分成了2块SBLIVE和SBROOT，我看了下我写入错误时的错误报告，提示是其中一块100M的SBLIVE分区满了无法写入，所以这个应该需要修改源代码，把这个分区改大一些

**Comment by OrdinaryChen** [comment]
或者说有没有办法手动的划分U盘


 
---Original---
From: ***@***.***&gt;
Date: 2021/6/9 15:26:04
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BluewhaleRobot/systemback] An error occured while unpacking the live system files (#13)




 
这个感觉跟sblive的文件大小有关
   
是太大了，虽然整体的大小限制没有了，但是单个文件不超过4G的限制还在。现在代码里面的做法是把home和独立出来压缩一个文件。所以home太大了还是不行。还有一个做法就是不生成iso文件直接利用sblive文件写入u盘。
  
我就是不保存iso直接写进世界写入u盘的，之前系统20多g的时候写成功了的，现在40多g之后就写不了了
  
这个写入U盘时，把U盘分成了2块SBLIVE和SBROOT，我看了下我写入错误时的错误报告，提示是其中一块100M的SBLIVE分区满了无法写入，所以这个应该需要修改源代码，把这个分区改大一些

**Comment by randoms** [comment]
可以看看这个 #10 ，因为我没遇到过这个问题所有一直没有merge

**Comment by renma1** [comment]
可以看看前面fredoule2k发的issue，改一下源代码里的分区大小，然后再重新编译一下

> 
> 大老，具体怎么操作啊…代码怎么改…
> […](#)
> ---Original--- From: ***@***.***&gt; Date: 2021/6/9 15:26:04 To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [BluewhaleRobot/systemback] An error occured while unpacking the live system files (#13) 这个感觉跟sblive的文件大小有关 是太大了，虽然整体的大小限制没有了，但是单个文件不超过4G的限制还在。现在代码里面的做法是把home和独立出来压缩一个文件。所以home太大了还是不行。还有一个做法就是不生成iso文件直接利用sblive文件写入u盘。 我就是不保存iso直接写进世界写入u盘的，之前系统20多g的时候写成功了的，现在40多g之后就写不了了 这个写入U盘时，把U盘分成了2块SBLIVE和SBROOT，我看了下我写入错误时的错误报告，提示是其中一块100M的SBLIVE分区满了无法写入，所以这个应该需要修改源代码，把这个分区改大一些 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by OrdinaryChen** [comment]
事实上现在出了一个新问题，我做了一个20多GB的镜像放进U盘里，然后不能把系统做到一个2T的机械硬盘里 ，但是可以做到500GB的固态了。不知道为啥了。。。

**Comment by OrdinaryChen** [comment]
> 可以看看前面fredoule2k大佬发的issue，改一下源代码里的分区大小，然后再重新编译一下
> 
> > 大老，具体怎么操作啊…代码怎么改…
> > […](#)
> > ---Original--- From: _**@**_._**> Date: 2021/6/9 15:26:04 To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [BluewhaleRobot/systemback] An error occured while unpacking the live system files (#13) 这个感觉跟sblive的文件大小有关 是太大了，虽然整体的大小限制没有了，但是单个文件不超过4G的限制还在。现在代码里面的做法是把home和独立出来压缩一个文件。所以home太大了还是不行。还有一个做法就是不生成iso文件直接利用sblive文件写入u盘。 我就是不保存iso直接写进世界写入u盘的，之前系统20多g的时候写成功了的，现在40多g之后就写不了了 这个写入U盘时，把U盘分成了2块SBLIVE和SBROOT，我看了下我写入错误时的错误报告，提示是其中一块100M的SBLIVE分区满了无法写入，所以这个应该需要修改源代码，把这个分区改大一些 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

有没有教程或者传送门？

**Comment by OrdinaryChen** [comment]
> > 可以看看前面fredoule2k大佬发的issue，改一下源代码里的分区大小，然后再重新编译一下
> > > 大老，具体怎么操作啊…代码怎么改…
> > > […](#)
> > > ---Original--- From: _**@**_._**> Date: 2021/6/9 15:26:04 To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [BluewhaleRobot/systemback] An error occured while unpacking the live system files (#13) 这个感觉跟sblive的文件大小有关 是太大了，虽然整体的大小限制没有了，但是单个文件不超过4G的限制还在。现在代码里面的做法是把home和独立出来压缩一个文件。所以home太大了还是不行。还有一个做法就是不生成iso文件直接利用sblive文件写入u盘。 我就是不保存iso直接写进世界写入u盘的，之前系统20多g的时候写成功了的，现在40多g之后就写不了了 这个写入U盘时，把U盘分成了2块SBLIVE和SBROOT，我看了下我写入错误时的错误报告，提示是其中一块100M的SBLIVE分区满了无法写入，所以这个应该需要修改源代码，把这个分区改大一些 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 有没有教程或者传送门？

fredoule2k大佬只是说了分析和想法，没有说咋改咋弄额。。。

**Comment by randoms** [comment]
已修复
