### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ghost** [BluewhaleRobot/systemback#14]
Can your modied version of systemback create a bootable iso over 4g? Because i tried manually in the terminal creating my linux distro into a bootable iso over 4gb using the mkisofs technique from the systembacks launchpad chat it works and boots into vmware but when installing into vmware and reboot the os goes black screen with an error....if i use your tool can it make one over 4gb and will it be installable?

**Comment by randoms** [comment]
Yes, over 4GB iso is supported
