### ISSUE TITLE
some questions expect your reply,thanks.

### ISSUE THREAD

**Issue by Jared-Shen** [BluewhaleRobot/systemback#2]
recently i have some problems when i want to backup my system ubuntu16.04 so i download software  systemback  on ubuntu16.04,as you know,systemback has stopped to maintain since 2018,and there are some problems remained to be solved. As is shown  below:

you see first problem is that it can’t detect NVME,you see that there exists only USB，the second problem is that it doesn’t have grub,so there are some problems to start the computer.

the first glance at this repository i was glad because it was updated recently,maybe it’s useful on ubuntu 16.04

but i didn’t see any describe about this,would you give me more details on this project?

**Comment by Jared-Shen** [comment]
![Uploading 87857613...]()

**Comment by randoms** [comment]
At present, I only add large file support to this project, and do not do anything special for NVME.
