### ISSUE TITLE
不能Convert to ISO

### ISSUE THREAD

**Issue by IricBing** [BluewhaleRobot/systemback#3]
按照流程安装，操作，一直都是很顺畅的，只有最后一步转化iso不行
![深度截图_选择区域_20200727163320](https://user-images.githubusercontent.com/22849596/88521377-67ae4e80-d027-11ea-93d1-107db5660d3d.png)
创建U盘启动盘是可以的，也能从U盘启动

**Comment by randoms** [comment]
你用是通过添加软件源安装的吗，截图被墙了，看不到。

**Comment by IricBing** [comment]
虽然这个按钮不能点，但是点完Create new之后在/home目录下就自动又demo.iso文件了，我正在测试这个iso文件，和教程上的一样，没有什么区别。万分感谢您的贡献

**Comment by byronsit** [comment]
我也出现了类似的情况。debuild安装的，一直都能用，这次用在一台ubuntu 18.04上，是灰色了。 把sblive拷贝到我平时用的电脑，发现也不能convert。
