### ISSUE TITLE
Can't find the USB M.2 hard drive

### ISSUE THREAD

**Issue by cyhasuka** [BluewhaleRobot/systemback#31]
Does this software will support M.2 sata hard drives?

**Comment by randoms** [comment]
M.2 SATA should already supported.

**Comment by cyhasuka** [comment]
Thanks for your reply.
The system can read the M.2 SATA hard drive but this option is not visible in the SystemBack, I don't know why.
The hard drive model is SAMSUNG MZNLN512HMJP-000H1,and the hard disk box is produced by UGreen, type CM238.

**Comment by misland** [comment]
> M.2 SATA should already supported.
hi bro,as @cyhasuka said,the system can find m2 sata,but the hard drive doesn't listed in the restore page
sorry for my terrible english,I am chinese too but I don't have chinese input on my system:(

**Comment by randoms** [comment]
Sorry, I don't have m2 device. So I can not test it right now.

**Comment by misland** [comment]
hi all,i found solution [here](https://gitee.com/bingobinlw/volans/issues/I17VOD)

**Comment by randoms** [comment]
Great, it also helps me to fix the issue

**Comment by cyhasuka** [comment]
> 大家好，我 [在这里找到了解决方案 ](https://gitee.com/bingobinlw/volans/issues/I17VOD)

THX,this solved my issue.
