### ISSUE TITLE
secret key  error, build failed

### ISSUE THREAD

**Issue by hezhenjiang** [BluewhaleRobot/systemback#40]
N: 4 tags overridden (4 warnings)                                                                                       Finished running lintian.                                                                                               Now signing changes and any dsc files...                                                                                 signfile dsc systemback_1.8.9.dsc Bluewhale Robot <randoms@bwbot.org>                                                  gpg: skipped "Bluewhale Robot <randoms@bwbot.org>": No secret key                                                       gpg: /tmp/debsign.Gu9ln7Mg/systemback_1.8.9.dsc: clear-sign failed: No secret key                                       debsign: gpg error occurred!  Aborting....                                                                              debuild: fatal error at line 1081:                                                                                      running debsign failed

**Comment by randoms** [comment]
That's normal, it's not an error. the deb files should already generated.
