### ISSUE TITLE
恢复系统后软链接变成硬链接

### ISSUE THREAD

**Issue by dzywater** [BluewhaleRobot/systemback#5]
Ubuntu20.04典型的就是系统恢复后/bin /lib /lib32 /lib64 /sbin都不再是软链接，从而占用了大量磁盘空间，当然不只是这几个目录，进去子目录后还有挺多。当基于恢复的系统再次备份系统时，备份的系统或iso就是很大。

**Comment by randoms** [comment]
感谢反馈，等我详细看看

**Comment by randoms** [comment]
已修复
