### ISSUE TITLE
nvme无法正常工作

### ISSUE THREAD

**Issue by randoms** [BluewhaleRobot/systemback#7]
- 无法正常分区
- 无法格式化分区

**Comment by Nova555** [comment]
请问你现在有找到解决方案吗？

**Comment by dzywater** [comment]
I got the same error.
![nvme cannot be formatted](https://user-images.githubusercontent.com/22073470/118268317-d0e84b00-b4ef-11eb-887e-ca1eb9cd385a.png)

**Comment by randoms** [comment]
fixed
