### ISSUE TITLE
the SBLIVE partition is too short

### ISSUE THREAD

**Issue by fredoule2k** [BluewhaleRobot/systemback#9]
It is a problem that I already saw in other forks : the SBLIVE partition size is hardcoded to 100MB, which is too short for some systems. For instance in my case (kubuntu 20) my latest .sblive 102MB are needed instead of the 100.

I had to change it and build from source an old version to get it working (I used 140MB)

I am testing right now if my new build based on your sources work and do a pull request 

However it might be more sensible to detect the size, based on the contents of the casper folder in the archive instead of a hardcoded value (unfortunately I don't have the knowledge and time to make such a change)

**Comment by randoms** [comment]
Thanks for your pull request, I haven't meet this problem before. I will review your changes when I'm free.

**Comment by randoms** [comment]
fixed
